---
language: node_js
node_js:
  - "7"

sudo: false

cache:
  directories:
    - node_modules
    - $HOME/.npm
    - $HOME/.cache # includes bowers cache
    - $HOME/.yarn-cache

env:
  - EMBER_TRY_SCENARIO=default
  - EMBER_TRY_SCENARIO=ember-release
  - EMBER_TRY_SCENARIO=ember-beta
  - EMBER_TRY_SCENARIO=ember-canary

matrix:
  fast_finish: true
  allow_failures:
    - env: EMBER_TRY_SCENARIO=ember-canary

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
  - yarn global add bower yarn phantomjs-prebuilt@2
  - phantomjs --version

install:
  - yarn upgrade
  - bower install

script:
  - node_modules/.bin/ember try:one $EMBER_TRY_SCENARIO test --skip-cleanup
